#!/bin/bash

declare -a jetbrains=(
  aqua datagrip dataspell goland
  idea phpstorm pycharm rubymine
  #clion #fleet #rider #rustrover #webstorm
)

for jetbra in "${jetbrains[@]}"; do
  if [[ -f "/opt/jetbrains/${jetbra}/bin/${jetbra}64.vmoptions" ]]; then
    TEST=$(grep -o "jetbra-agent.jar" "/opt/jetbrains/${jetbra}/bin/${jetbra}64.vmoptions")
    if [[ "${TEST}" != "jetbra-agent.jar" ]]; then
      echo "-javaagent:/opt/jetbrains/jetbra/jetbra-agent.jar" >> "/opt/jetbrains/${jetbra}/bin/${jetbra}64.vmoptions"
      echo "patched ${jetbra}64.vmoptions"
    fi
  fi
done